---
development:
  cloud_name: vipvex
  api_key: '367529171289133'
  api_secret: yOjAYtE8GUEDkXv77LSItWOkYzg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: vipvex
  api_key: '367529171289133'
  api_secret: yOjAYtE8GUEDkXv77LSItWOkYzg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: vipvex
  api_key: '367529171289133'
  api_secret: yOjAYtE8GUEDkXv77LSItWOkYzg
  enhance_image_tag: true
  static_image_support: false
